eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8095/eureka/
feign:
    client:
        config:
            default:
                connectTimeout: 500000
                readTimeout: 1000000
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8181
spring:
    application:
        name: account-server
    cloud:
        alibaba:
            seata:
                tx-service-group: crm_tx_group
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: lhy@123
        url: jdbc:mysql://localhost:3306/account?serverTimezone=GMT%2B8
        username: root
